### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by LeoLampio** [tiikerikakku/korttelilainaamo#1]
Applikaatio on selvästi vielä hyvin kesken.

- Koodia ei olla jaettu eri moduuleihin (esim. käyttäjät, esineet)
- Rekisteröinnissä tai esineen lisäämisessä ei mm. tarkisteta käyttäjän syötteen pituutta
- Linkkiä klikattaessa sivu avautuu uuteen välilehteen, mikä on hieman ärsyttävää
- Tietoturva on puutteellinen (CSRF haavoittuvuus)
- Tietokanta vaikuttaa suunnitelman perusteella ehkä hieman liian pieneltä
- Commitit ovat muuten hyvät, mutta yhdessä commitissa on selvästi liikaa tavaraa

- Ulkoasu näyttää siistiltä

**Comment by tiikerikakku** [comment]
Kiitos arvioinnista, pidetään asiat mielessä. Sovellus on tosiaan vielä _hyvin kesken_. Katsotaan nyt mitä ehtii tehdä...
