### ISSUE TITLE
vertaisarviointi 2

### ISSUE THREAD

**Issue by Karri6** [tiikerikakku/korttelilainaamo#2]
Sain tietokannat kopioitua ja ohjelman pyörimään, uutta käyttäjää rekisteröidessä tuli kuitenkin virheilmoitus:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

Veikkaan kuitenkin, että ongelma minun puolellani.  

Koodi on siistiä ja olitkin kommentoinut routes.py tiedoston alkuun tieodoston jakamisesta osiin luettavuuden parantamiseksi.
Projekti on kokonaisvaltaisesti hyvällä mallilla, kiireen puitteissa itselläkin jäänyt aivan viimetinkaan nuo samat asiat, jotka olit maininnut ReadMe tiedoston alussa. 

Tsemppiä loppukiristykseen!

**Comment by tiikerikakku** [comment]
Kiitos arvioinnista!
